---
title: "RAP Self Assessment"
format:
  html:
    theme: [default, styles.scss]
    title-block-banner: true
    template-partials: partials/title-block.html
    logo: images/SG-logo.jpg
    toc: true
    toc-depth: 3
    toc-location: left
    toc-title: "Contents"
    anchor-sections: false
    smooth-scroll: true
    header-includes: |
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
embed-resources: true
server: shiny
---

```{r setup, include = FALSE}
#| context: setup

# Load packages
library(shiny)
library(dplyr)
library(tidyr)
library(here)
library(readr)
library(purrr)
library(tibble)
library(stringr)
library(knitr)

# Load Shiny modules
walk(list.files("modules", ".R$", full.names = TRUE), source)

# Read in criteria list
criteria <- read_rds(here("data", "criteria.rds"))

# Check help text available for all criteria
if(any(!criteria$id %in% str_extract(list.files(here("quarto-docs", "help")), 
                                     "id_\\d+_\\d+"))) {
   stop("All IDs in `data/criteria.rds` must have a corresponding file in ", 
        "`quarto-docs/help/`.")
}

# Read in lookup data
all_options <- read_rds(here("data", "options.rds"))
all_levels  <- read_rds(here("data", "levels.rds"))

# Set project directory as root when using knit_child
opts_knit$set(root.dir = here())
```


## About this tool

```{r about, results = "asis", warning = FALSE}
cat(knit_child(here("quarto-docs", "_about-this-tool.qmd"),
                 envir = environment(),
                 quiet = TRUE))
```


## Self assessment


### About your project

```{r metadata}
metadata_ui("metadata")
```


```{r form, results = "asis", warning = FALSE}
out <- map(
   all_levels,
   function(level) {
      knit_child(here("quarto-docs", "_level-form.qmd"),
                 envir = environment(),
                 quiet = TRUE)
   }
)

cat(unlist(out), sep = "\n")
```


## Download report

```{r download}
tagList(
   download_report_ui("report"),
   download_csv_ui("csv")
)
```


## Further support

```{r support, results = "asis", warning = FALSE}
cat(knit_child(here("quarto-docs", "_further-support.qmd"),
                 envir = environment(),
                 quiet = TRUE))
```


## Licence

All content is available under the [Open Government Licence v3.0](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/), except where otherwise stated.


<!-- Shiny server -->

```{r server}
#| context: server

form_responses <- map(
   set_names(unique(criteria$id)),
   ~ possibly(callModule)(form_server, .x)
)

data_output <- reactive({
   
   form_responses <- map_dfr(form_responses, ~ .x(), .id = "id")
   
   criteria |>
      left_join(form_responses, by = "id") |>
      mutate(
         status = replace_na(status, "not_assessed"),
         status_label = case_when(
            status == "not_assessed" ~ "Not assessed",
            TRUE ~ names(all_options)[match(status, all_options)]
         )
      )
   
})

metadata <- callModule(metadata_server, "metadata")

callModule(download_csv_server, "csv", data_output, all_levels)

callModule(download_report_server, "report", data_output, metadata)
```
