This tool is for analysts in the Scottish Government developing [Reproducible Analytical Pipelines](https://analysisfunction.civilservice.gov.uk/support/reproducible-analytical-pipelines/). It aims to help analysts identify both areas of success and potential improvements.

There are four levels of RAP maturity:

* Aspiring

* Fundamental

* Intermediate

* Advanced

### How to complete the self assessment {.unlisted}

Mark the criteria in each level as 'Complete', 'In progress' or 'Not started'. It isn't essential to provide a marking for all criteria. 

Next, download a report to see what level of RAP maturity you are currently working at. You can also download a csv file containing your self assessment markings. Note that the tool doesn't store any data, so make sure to download a report or csv to save for future reference. 

You can use your report to:

* understand where you are already following RAP principles

* understand what RAP principles you should focus on next

It might be useful to complete this self assessment every few months to track progress and prioritise next steps.

### Feedback {.unlisted}

This is a new tool and we would welcome any feedback you have. Please [file an issue on GitHub](https://github.com/ScotGovAnalysis/rap-self-assessment/issues) or [get in touch via email](mailto:alice.byers@gov.scot;thomas.wilson@gov.scot?subject=RAP%20Self-Assessment%20Feedback).