---
title: "RAP Self Assessment Report"
output: 
  html_document:
    css: "md_styles.css"
params:
  input_data: NA
  all_options: NA
  all_levels: NA
  metadata: NA
editor_options: 
  chunk_output_type: console
---

```{r echo = FALSE, include = FALSE}
library(dplyr)
library(tidyr)
library(gt)
library(janitor)
library(ggplot2)
library(sgplot)

source(here::here("functions", "level_label.R"))
```

**Publication title**: `r params$metadata$pub_name`

**Team leader**: `r params$metadata$team_lead`

**Team members**: `r params$metadata$team_members`

**Report produced**: `r format(lubridate::today(), "%d %B %Y")`


## Level of RAP

```{r, echo = FALSE, include = FALSE}
level_summary <-
  params$input_data |>
  select(level, status) |> 
  mutate(n = 1) |>
  complete(level, status = params$all_options, fill = list(n = 0)) |>
  pivot_wider(names_from = status, names_expand = TRUE,
              values_from = n, values_fn = sum, values_fill = 0) |>
  rowwise() |>
  mutate(n_criteria = sum(c_across(!level))) |>
  ungroup() |>
  mutate(
    all_criteria = yes == n_criteria & n_criteria > 0,
    level_met = accumulate(all_criteria, all),
    perc_met = yes / n_criteria,
    perc_in_progress = progress / n_criteria
  )

max_level <- ifelse(
  any(level_summary$level_met),
  level_summary |> filter(level_met) |> pull(level) |> max(),
  NA
)

level_met_text <- ifelse(
  is.na(max_level),
  paste("is working towards", 
        level_label(min(params$all_levels), params$all_levels)),
  paste("has met level", 
        level_label(max_level, params$all_levels))
)
```

This publication `r level_met_text`.

```{r, echo = FALSE, dev = "svg", fig.align = "center", fig.width = mm_to_inch(250), fig.height = mm_to_inch(150)}
chart_data <- 
  level_summary |>
  select(level, perc_met, perc_in_progress, all_criteria, level_met) %>%
  mutate(level = factor(level,
                        rev(params$all_levels),
                        label = rev(level_label(level, params$all_levels))))

chart_data %>%
  pivot_longer(cols = starts_with("perc"), 
               names_to = "status", 
               values_to = "perc") %>%
  mutate(status = factor(status, levels = c("perc_in_progress", "perc_met"))) %>%
  ggplot(aes(y = level)) +
  geom_col(data = chart_data, aes(x = 1),
           fill = "white",  
           colour = sg_colour_values["dark-blue"]) +
  geom_col(aes(x = perc, fill = status)) +
  scale_fill_discrete_sg(
    reverse = TRUE,
    guide = guide_legend(reverse = TRUE),
    labels = c("perc_met" = "Criteria Met", "perc_in_progress" = "Criteria in progress")) +
  scale_x_continuous(labels = scales::percent) +
  theme_sg(base_size = 16, legend = "bottom") +
  labs(x = "Percentage of criteria", y = NULL, fill = NULL)
```

<br>

```{r, echo = FALSE}
level_summary |>
  select(level, all_of(params$all_options), perc_met) |>
  gt() |>
  tab_spanner(
    label = "Number of criteria",
    columns = any_of(names(params$all_options))
  ) |>
  cols_label(level = "Level of RAP",
             perc_met = "Percentage of criteria met") |>
  fmt_percent(perc_met, decimals = 0)
```


## Assessment by Level 

```{r, echo=FALSE, results='asis'}
out <- 
  map(
    unique(params$input_data$level),
    function(x) {
      knitr::knit_child('level-progress.Rmd', 
                        envir = environment(), 
                        quiet = TRUE)
    }
  )

cat(unlist(out), sep = "\n")
```